# [START runtime]

# App engine language.
runtime: nodejs
# Set environment to flexible.
env: flex

# Service scaling settings
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

# Environment Variables
env_variables:
  NODE_ENV: 'production'

# [END runtime]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - ^backup$
 - ^test$
 - ^src$
 - ^npm-debug.log

# For detailed information related to app.yaml file visit this link
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
