
export const CLASSROOM_COURSES_FETCH = 'CLASSROOM_COURSES_FETCH';
export const CLASSROOM_COURSES_FETCH_START = 'CLASSROOM_COURSES_FETCH_START';
export const CLASSROOM_COURSES_FETCH_SUCCESS = 'CLASSROOM_COURSES_FETCH_SUCCESS';
export const CLASSROOM_COURSES_FETCH_ERROR = 'CLASSROOM_COURSES_FETCH_ERROR';
