
export const CLASSROOM_COURSES_GET_START = 'CLASSROOM_COURSES_GET_START';
export const CLASSROOM_COURSES_GET_SUCCESS = 'CLASSROOM_COURSES_GET_SUCCESS';
export const CLASSROOM_COURSES_GET_ERROR = 'CLASSROOM_COURSES_GET_ERROR';
