
export const COURSES_GET = 'COURSE_GET';
export const COURSE_GET = 'COURSE_GET';
export const COURSE_CREATE = 'COURSE_CREATE';
export const COURSE_UPDATE = 'COURSE_UPDATE';
export const COURSE_DELETE = 'COURSE_DELETE';


export const MODULES_GET = 'MODULE_GET';
export const MODULE_GET = 'MODULE_GET';
export const MODULE_CREATE = 'MODULE_CREATE';
export const MODULE_UPDATE = 'MODULE_UPDATE';
export const MODULE_DELETE = 'MODULE_DELETE';


export const QUESTIONS_GET = 'QUESTION_GET';
export const QUESTION_GET = 'QUESTION_GET';
export const QUESTION_CREATE = 'QUESTION_CREATE';
export const QUESTION_UPDATE = 'QUESTION_UPDATE';
export const QUESTION_DELETE = 'QUESTION_DELETE';




export const COURSE_CREATE_START = 'COURSE_CREATE_START';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_ERROR = 'COURSE_CREATE_ERROR';

export const COURSES_GET_START = 'COURSES_GET_START';
export const COURSES_GET_SUCCESS = 'COURSES_GET_SUCCESS';
export const COURSES_GET_ERROR = 'COURSES_GET_ERROR';

export const COURSE_GET_START = 'COURSE_GET_START';
export const COURSE_GET_SUCCESS = 'COURSE_GET_SUCCESS';
export const COURSE_GET_ERROR = 'COURSE_GET_ERROR';

export const COURSE_UPDATE_START = 'COURSE_UPDATE_START';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_ERROR = 'COURSE_UPDATE_ERROR';

export const MODULE_CREATE_START = 'MODULE_CREATE_START';
export const MODULE_CREATE_SUCCESS = 'MODULE_CREATE_SUCCESS';
export const MODULE_CREATE_ERROR = 'MODULE_CREATE_ERROR';


export const MODULES_GET_START = 'MODULES_GET_START';
export const MODULES_GET_SUCCESS = 'MODULES_GET_SUCCESS';
export const MODULES_GET_ERROR = 'MODULES_GET_ERROR';

export const MODULE_GET_START = 'MODULE_GET_START';
export const MODULE_GET_SUCCESS = 'MODULE_GET_SUCCESS';
export const MODULE_GET_ERROR = 'MODULE_GET_ERROR';

export const MODULE_UPDATE_START = 'MODULE_UPDATE_START';
export const MODULE_UPDATE_SUCCESS = 'MODULE_UPDATE_SUCCESS';
export const MODULE_UPDATE_ERROR = 'MODULE_UPDATE_ERROR';
