
export const COURSES_FETCH_START = 'COURSES_FETCH_START';
export const COURSES_FETCH_SUCCESS = 'COURSES_FETCH_SUCCESS';
export const COURSES_FETCH_ERROR = 'COURSES_FETCH_ERROR';

export const COURSE_FETCH_START = 'COURSE_FETCH_START';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const COURSE_FETCH_ERROR = 'COURSE_FETCH_ERROR';

export const COURSE_UPDATE_START = 'COURSE_UPDATE_START';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_ERROR = 'COURSE_UPDATE_ERROR';

export const MODULE_CREATE_START = 'MODULE_CREATE_START';
export const MODULE_CREATE_SUCCESS = 'MODULE_CREATE_SUCCESS';
export const MODULE_CREATE_ERROR = 'MODULE_CREATE_ERROR';


export const MODULES_FETCH_START = 'MODULES_FETCH_START';
export const MODULES_FETCH_SUCCESS = 'MODULES_FETCH_SUCCESS';
export const MODULES_FETCH_ERROR = 'MODULES_FETCH_ERROR';

export const MODULE_FETCH_START = 'MODULE_FETCH_START';
export const MODULE_FETCH_SUCCESS = 'MODULE_FETCH_SUCCESS';
export const MODULE_FETCH_ERROR = 'MODULE_FETCH_ERROR';

export const MODULE_UPDATE_START = 'MODULE_UPDATE_START';
export const MODULE_UPDATE_SUCCESS = 'MODULE_UPDATE_SUCCESS';
export const MODULE_UPDATE_ERROR = 'MODULE_UPDATE_ERROR';
