
export const USER_SIGN_IN_START = 'USER_SIGN_IN_START';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const USER_GET_START = 'USER_GET_START';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';

export const ELEMENT_GET_START = 'ELEMENT_GET_START';
export const ELEMENT_GET_SUCCESS = 'ELEMENT_GET_SUCCESS';
export const ELEMENT_GET_ERROR = 'ELEMENT_GET_ERROR';
